[tool.poetry]
name = "gym-microrts"
version = "0.0.0"
description = ""
authors = ["Costa Huang <costa.huang@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.7"
gym = "^0.18.3"
JPype1 = "^1.3.0"
uvicorn = {version = "^0.14.0", extras = ["api"]}
fastapi = {version = "^0.67.0", extras = ["api"]}

[tool.poetry.dev-dependencies]
poetry-dynamic-versioning = "^0.13.0"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry-dynamic-versioning.substitution]
files = ["*/__init__.py"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

